# Example SuperCensor PenaltyPointsRule.
# For more informations and complete tutorial please visit: https://github.com/Wruczek/SuperCensor/wiki

PenaltyPointsRules:
  # Rule name
  KickPlayer:
    # Activate this check when player have 100 PenaltyPoints.
    ActivateOn: 100
    RunCommands:
      - "kick %nick% [SC] Please calm down and stop breaking chat rules or you will be temporary muted."
    # You can log everything into files, if you want
    # Remove this line to stop logging about this rule
    Log: "Player %nick% has been kicked for receiving 100 PenaltyPoints"
