# An actual list of English swear words with regex to use with SuperCensor.
# Copyright (C) 2013 Alison Gianotto - snipe@snipe.net - MIT License
# Edited and translated to RegEx by Wruczek for SuperCensor project.
Wordlist: 
  - "[@a][zs5][zs5](h[0o][l1]e)?"
  - "f[uv](c)?k"
  - "[a@][nm][a@][l1]"
  - "[a@][nm][uv][sz5$]"
  - "b[a@][sz5$]t[a@]rd"
  - "b[i1]tc[h#]"
  - "b[o0][o0]b"
  - "c[o0]ck"
  - "c[uv][mn]"
  - "c[uv][nm]t"
  - "d[i1]ck"
  - "d[i1][l1]d[o0]"
  - "dyk[e3]"
  - "f[a@]g"
  - "f[a@]gg[o0]t"
  - "[h#][a@][nm]dj[o0]b"
  - "[h#][o0][mn][o0]"
  - "j[i1][zs5][zs5]"
  - "k[i1]k[e3]"
  - "k[uv][nm]t"
  - "[mn][uv]ff"
  - "[nm][i1]gg[e3]r"
  - "[pq][e3][nm][i1][sz5$]"
  - "[pq][i1][sz5$][sz5$]"
  - "[pq][o0][o0][pq]"
  - "[pq][uv][sz5$][sz5$]y"
  - "[qp][uv][e3][e3]r"
  - "r[a@][pq][e3]"
  - "[sz5$][e3][mn][e3][nm]"
  - "[sz5$][e3]x"
  - "[sz5$][h#][i1]t"
  - "[sz5$][l1][uv]t"
  - "t[i1]tt[i1][e3][sz5$]"
  - "t[wv][a@]t"
  - "[vu][a@]g[i1][nm][a@]"
  - "[vu][uv][l1][vu][a@]"
  - "[wv][a@][nm]k"
  - "[a@][nm][a@][l1][pq][l1][uv]g"
  - "[a@][nm][a@][l1][sz5$][e3]x"
  - "[a@]r[sz5$][e3]"
  - "[a@][sz5$][sz5$][a@][sz5$][sz5$][i1][nm]"
  - "b[a@][l1][l1][sz5$]"
  - "b[i1][mn]b[o0]"
  - "b[l1][o0][o0]dy"
  - "b[l1][o0][o0]dy[h#][e3][l1][l1]"
  - "b[l1][o0][wv]j[o0]b"
  - "b[o0][l1][l1][o0]ck[sz5$]"
  - "b[o0][nm][e3]r"
  - "b[o0][o0]b[i1][e3][sz5$]"
  - "b[o0][o0]b[sz5$]"
  - "b[uv]gg[e3]r"
  - "b[uv]kk[a@]k[e3]"
  - "b[uv][l1][l1][sz5$][h#][i1]t"
  - "c[h#][i1][nm]k"
  - "c[l1][i1]t"
  - "c[l1][i1]t[o0]r[i1][sz5$]"
  - "c[o0]ck[sz5$][uv]ck[e3]r"
  - "c[o0][nm]d[o0][mn]"
  - "c[o0][o0][nm]"
  - "cr[a@][pq]"
  - "c[uv][mn][sz5$][h#][o0]t"
  - "d[a@][mn][mn]"
  - "d[a@][mn][mn][i1]t"
  - "d[a@][mn][nm]"
  - "d[i1]ck[h#][e3][a@]d"
  - "d[o0]ggy[sz5$]ty[l1][e3]"
  - f0ck
  - "f[a@]g[sz5$]"
  - "f[a@][nm][nm]y"
  - fck
  - "fck[e3]r"
  - fckr
  - "fck[uv]"
  - "fc[uv]k"
  - "f[uv]ck[e3]r"
  - "f[uv]ckf[a@]c[e3]"
  - "f[uv]ckr"
  - "f[uv]ct"
  - "g[e3][nm][i1]t[a@][l1]"
  - "g[e3][nm][i1]t[a@][l1][i1][a@]"
  - "g[e3][nm][i1]t[a@][l1][sz5$]"
  - "g[l1][o0]ry [h#][o0][l1][e3]"
  - "g[l1][o0]ry[h#][o0][l1][e3]"
  - "g[o0]b[sz5$][h#][i1]t[e3]"
  - "g[o0]d[a@][mn][mn][e3]t"
  - "g[o0]d[a@][mn][mn][i1]t"
  - "g[o0]dd[a@][mn][mn][e3]t"
  - "g[o0]dd[a@][mn][mn][i1]t"
  - "g[o0]dd[a@][mn][nm]"
  - "gy[pq][o0]"
  - "[h#][i1]t[l1][e3]r"
  - "[h#][o0][o0]k[e3]r"
  - "[h#][o0]r[e3]"
  - "[h#][o0]r[nm]y"
  - "j[e3][sz5$][uv][sz5$][sz5$][uv]ck[sz5$]"
  - "j[i1][zs5][zs5][uv][mn]"
  - "k[a@]ff[i1]r"
  - "[l1][e3][sz5$]b[o0]"
  - "[mn][a@][sz5$]t[uv]rb[a@]t[e3]"
  - "[mn][i1][l1]f"
  - "[mn][o0][l1][e3][sz5$]t"
  - "[mn][o0]r[o0][nm]"
  - "[mn][o0]t[h#][e3]rf[uv]ck"
  - "[mn]t[h#]rfckr"
  - "[nm][a@][zs5][i1]"
  - "[nm][e3]gr[o0]"
  - "[nm][i1]gg[a@]"
  - "[nm][i1]gg[a@][h#]"
  - "[nm][o0][nm]c[e3]"
  - "[pq][a@][e3]d[o0]"
  - "[pq][a@][e3]d[o0][pq][h#][i1][l1][e3]"
  - "[pq][a@]k[i1]"
  - "[pq][e3]ck[e3]r"
  - "[pq][e3]d[o0]"
  - "[pq][e3]d[o0]f[i1][l1][e3]"
  - "[pq][e3]d[o0][pq][h#][i1][l1][e3]"
  - "[pq][h#][uv]k"
  - "[pq][i1][mn][pq]"
  - "[pq][o0][o0]f"
  - "[pq][o0]r[nm]"
  - "[pq]r[i1]ck"
  - "[pq]r[o0][nm]"
  - "[pq]r[o0][sz5$]t[i1]t[uv]t[e3]"
  - "r[a@][pq][e3]d"
  - "r[a@][pq][e3][sz5$]"
  - "r[a@][pq][i1][sz5$]t"
  - "[sz5$]c[h#][l1][o0][nm]g"
  - "[sz5$]cr[o0]t[uv][mn]"
  - "[sz5$][h#][a@]g"
  - "[sz5$][h#][e3][mn][a@][l1][e3]"
  - "[sz5$][h#][i1]t[e3]"
  - "[sz5$][h#][i1][zs5]"
  - "[sz5$][l1][a@]g"
  - "[sz5$][pq][a@][sz5$]t[i1]c"
  - "[sz5$][pq][a@][zs5]"
  - "[sz5$][pq][e3]r[mn]"
  - "[sz5$][pq][uv][nm]k"
  - "[sz5$]tr[i1][pq][pq][e3]r"
  - "t[a@]rt"
  - "t[i1]t[sz5$]"
  - "t[i1]ttyf[uv]ck"
  - "t[o0][sz5$][sz5$][e3]r"
  - "t[uv]rd"
  - "[vu][a@]g[i1][nm][a@][l1]"
  - "[vu][i1]br[a@]t[o0]r"
  - "[wv][a@][nm]k[e3]r"
  - "[wv][e3][e3]d"
  - "[wv][e3]tb[a@]ck"
  - "[wv][h#][o0]r"
  - "[wv][h#][o0]r[e3]"
  - "[wv][o0]g"
  - "[a@]b[o0]rt[i1][o0][nm]"
  - "b[e3][a@][sz5$]t[i1][a@][l1][i1]ty"
  - "b[e3][sz5$]t[i1][a@][l1][i1]ty"
  - "b[e3][wv]b"
  - "b[l1][o0][wv]"
  - "b[l1][uv][mn][pq]k[i1][nm]"
  - "c[a@][wv]k"
  - "c[h#][o0][a@]d"
  - "c[o0][o0]t[e3]r"
  - "c[o0]r[nm][h#][o0][l1][e3]"
  - "d[o0][nm]g"
  - "d[o0][uv]c[h#][e3]"
  - "f[a@]rt"
  - "f[o0]r[e3][sz5$]k[i1][nm]"
  - "g[a@][nm]gb[a@][nm]g"
  - "g[o0][o0]k"
  - "[h#][o0][nm]k[e3]y"
  - "[h#][uv][mn][pq][i1][nm]g"
  - "j[i1][zs5]"
  - "[l1][a@]b[i1][a@]"
  - "[nm][uv]t[sz5$][a@]ck"
  - "[pq][o0][o0][nm]"
  - "[pq][uv][nm][a@][nm][i1]"
  - "[qp][uv][e3][e3]f"
  - "[qp][uv][i1][mn]"
  - "r[e3]ct[a@][l1]"
  - "r[e3]ct[uv][mn]"
  - "r[i1][mn]j[o0]b"
  - "[sz5$][pq][i1]ck"
  - "[sz5$][pq][o0][o0]"
  - "[sz5$][pq][o0][o0]g[e3]"
  - "t[a@][i1][nm]t"
  - "t[i1]tty"
  - "[vu][a@]g"
